apiVersion: v1
kind: Service
metadata:
  name: password-generator-service
spec:
  type: LoadBalancer
  selector:
    app: password-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
